# Generated by Django 2.2.19 on 2021-03-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('whatsapp', models.CharField(max_length=20)),
                ('twitter', models.CharField(max_length=120)),
                ('facebook', models.CharField(max_length=120)),
                ('instagram', models.CharField(max_length=120)),
                ('linkedin', models.CharField(max_length=120)),
                ('tiktok', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'contatos',
            },
        ),
    ]
