# Generated by Django 3.1.7 on 2021-03-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='facebook',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contato',
            name='instagram',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contato',
            name='linkedin',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tiktok',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contato',
            name='twitter',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contato',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
